image: docker

services:
    - name: docker:dind

variables:
    DOCKER_TLS_CERTDIR: ''
    # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_HOST: 'tcp://docker:2375'
    BUILD_TAG: 'gitlab-ee.webbylab.com:5050/ccdb/exchange-analyzer/backend'

stages:
    - build

before_script:
    - export BUILD_TAG=$CI_REGISTRY_IMAGE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: build
    script:
        - docker build -t $BUILD_TAG .
        - docker push $BUILD_TAG
    only:
        - main
        - develop
        - /^release\/.*$/
        - tags
