image: docker:23.0.6

services:
    - docker:23.0.6-dind

variables:
    PROJECT_NAME: ccdb
    PATH_TO_COMPOSE: ./docker/ci/docker-compose.yml
    BACKEND_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    BACKEND_CONTAINER_NAME: ccdb-be
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: 'tcp://docker:2375'

stages:
    - push

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

docker_build_push:
    stage: push
    script:
        - docker compose --project-name "$PROJECT_NAME" --file "$PATH_TO_COMPOSE" build
        - docker compose --project-name "$PROJECT_NAME" --file "$PATH_TO_COMPOSE" push
    only:
        - main
        - develop
        - /^release\/.*$/
        - tags
