version: '3.9'

services:
    be:
        image: ${BUILD_TAG}
        container_name: ccdb
        depends_on: ['test-db']
        environment:
            TZ: Europe/Kiev
            MODE: application
        env_file: .env.ci
    postgres:
        image: postgres:15
        command: --default-authentication-plugin=mysql_native_password --skip-log-bin --disable-log-bin
        restart: always
        environment:
            POSTGRES_DATABASE: ccdb_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_ROOT_PASSWORD: password
        container_name: ccdb-test-db

