version: '3.9'

services:
    be:
        image: ${BUILD_TAG}
        container_name: ccdb
        depends_on: ['test-db']
        environment:
            MODE: application
        env_file: .env.ci
    postgres:
        image: timescale/timescaledb:latest-pg15
        restart: always
        environment:
            POSTGRES_DATABASE: ccdb_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        container_name: ccdb-test-db

