export const MILLISECONDS_IN_A_SECOND = 1000;

export const MILLISECONDS_IN_A_MINUTE = 60000;

export const MILLISECONDS_IN_AN_HOUR = 3600000;

export const MINUTES_IN_AN_HOUR = 60;

export const SECONDS_IN_A_MINUTE = 60;
