const EXCEPTION_CODES = {
    FORMAT_ERROR: 'FORMAT_ERROR',

    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    MUTEX_TIMEOUT_EXCEEDED: 'MUTEX_TIMEOUT_EXCEEDED',
    COLLECTORS_SCHEDULER_FAILURE: 'COLLECTORS_SCHEDULER_FAILURE',
    COLLECTORS_MANAGER_FAILURE: 'COLLECTORS_MANAGER_FAILURE',
    MARKET_MANAGER_FAILURE: 'MARKET_MANAGER_FAILURE',

    ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
    ENTITY_NOT_UNIQUE: 'ENTITY_NOT_UNIQUE',
    INVALID_RELATION: 'INVALID_RELATION',
    ENTITY_IS_REFERENCED: 'ENTITY_IS_REFERENCED',

    RABBIT_CHANNEL_IS_CLOSED: 'RABBIT_CHANNEL_IS_CLOSED',

    SERVER_ERROR: 'SERVER_ERROR',
};

export default EXCEPTION_CODES;
