version: '3.9'

x-backend-body: &backend-body
    image: ${BE_REGISTRY_ADDRESS}:${BE_TAG}
    depends_on:
        timescale:
            condition: service_healthy
        redis:
            condition: service_healthy
        rabbitmq:
            condition: service_healthy
    env_file: ./env/.env.backend
    volumes:
        - ../:/app
        - /app/node_modules

services:
    backend:
        <<: *backend-body
        build:
            context: ../
            dockerfile: ./docker/config/backend/Dockerfile
            args:
                PORT: 8000
        container_name: ccdb-backend
        ports: ['8000:8000']
        command: sh -c "npm run nodemon"

    # ccxt-collectors-1:
    #     <<: *backend-body
    #     container_name: ccdb-ccxt-collectors-1
    #     environment:
    #         CCXT_INSTANCE_POSITION: 0
    #         CCXT_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:ccxt-collectors"

    # ccxt-collectors-2:
    #     <<: *backend-body
    #     container_name: ccdb-ccxt-collectors-2
    #     environment:
    #         CCXT_INSTANCE_POSITION: 1
    #         CCXT_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:ccxt-collectors"

    # xrpl-collectors-1:
    #     <<: *backend-body
    #     container_name: ccdb-xrpl-collectors-1
    #     environment:
    #         XRPL_INSTANCE_POSITION: 0
    #         XRPL_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:xrpl-collectors"

    # eth-collectors-1:
    #     <<: *backend-body
    #     container_name: ccdb-eth-collectors-1
    #     environment:
    #         ETH_INSTANCE_POSITION: 0
    #         ETH_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:eth-collectors"

    # tezos-collectors-1:
    #     <<: *backend-body
    #     container_name: ccdb-tezos-collectors-1
    #     environment:
    #         TEZOS_INSTANCE_POSITION: 0
    #         TEZOS_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:tezos-collectors"

    # cardano-collectors-1:
    #     <<: *backend-body
    #     container_name: ccdb-cardano-collectors-1
    #     environment:
    #         CARDANO_INSTANCE_POSITION: 0
    #         CARDANO_REPLICA_SIZE: 2
    #     command: sh -c "npm run cli:cardano-collectors"

    database-writer:
        <<: *backend-body
        container_name: ccdb-database-writer
        command: sh -c "npm run workers:database-writer:nodemon"

    markets-refresher:
        <<: *backend-body
        container_name: ccdb-markets-refresher
        command: sh -c "npm run workers:markets-refresher:nodemon"

    timescale:
        image: timescale/timescaledb:2.11.1-pg15
        container_name: ccdb-timescale
        restart: always
        ports: ['5432:5432']
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d ccdb -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        env_file: ./env/.env.timescale
        command: postgres -c 'max_connections=500'
        volumes:
            - ~/docker-volumes/ccdb/timescale:/var/lib/postgresql/data

    timescale-test:
        image: timescale/timescaledb:2.11.1-pg15
        container_name: ccdb-timescale-test
        restart: always
        ports: ['5431:5432']
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d ccdb_test -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        env_file: ./env/.env.timescale-test
        command: postgres -c 'max_connections=500'
        volumes:
            - ~/docker-volumes/ccdb/timescale-test:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3.12.0-management
        container_name: ccdb-rabbitmq
        hostname: 'dev-rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        env_file: ./env/.env.rabbitmq
        volumes:
            - '~/docker-volumes/ccdb/rabbitmq:/var/lib/rabbitmq'
    
    redis:
        image: redis:7.2.3
        container_name: ccdb-redis
        ports: ['6379:6379']
        command:
            - /bin/sh
            - -c
            - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        env_file: ./env/.env.redis
        volumes:
            - '~/docker-volumes/ccdb/redis:/data'
