version: '3.9'

services:
    backend:
        build:
            context: ../
            dockerfile: ./docker/config/backend/Dockerfile
            args:
                PORT: 8000
        container_name: ccdb-backend
        ports: ['8000:8000']
        image: ${BE_REGISTRY_ADDRESS}:${BE_TAG}
        depends_on:
            timescale:
                condition: service_healthy
        environment:
            MODE: application
        env_file: ./env/.env.backend
        command: sh -c "npm run nodemon"
        volumes:
            - ../:/app
            - /app/node_modules


    collectors:
        image: ${BE_REGISTRY_ADDRESS}:${BE_TAG}
        container_name: ccdb-collectors
        depends_on:
            timescale:
                condition: service_healthy
        env_file: ./env/.env.backend
        command: sh -c "npm run collector:run"
        volumes:
            - ../:/app
            - /app/node_modules

    timescale:
        image: timescale/timescaledb:latest-pg15
        container_name: ccdb-timescale
        restart: always
        ports: ['5432:5432']
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d ccdb -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        env_file: ./env/.env.database
        command: postgres -c 'max_connections=500'
        volumes:
            - ~/docker-volumes/ccdb/database:/var/lib/postgresql/data

    timescale-test:
        image: timescale/timescaledb:latest-pg15
        container_name: ccdb-timescale-test
        restart: always
        ports: ['5431:5432']
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d ccdb_test -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        env_file: ./env/.env.database
        volumes:
            - ~/docker-volumes/ccdb/timescale-test:/var/lib/postgresql/data
