version: '3.3'

services:
    app:
        build: 
            context: ./../
            dockerfile: Dockerfile
        container_name: ccdb
        ports: [ '8000:8000', '3002:3002' ]
        depends_on: ['db']
        volumes:
          - ./../:/app
          # - ~/docker-volumes/ccdb/be/node_modules:/app/node_modules
        environment:
            MODE: application
        command: sh -c "npm i && rm -rf node_modules/multer/node_modules/busboy && npm run nodemon"
    db:
        image: timescale/timescaledb:latest-pg15
        restart: always
        ports: ['5432:5432']
        environment:
            POSTGRES_DB: ccdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_ROOT_PASSWORD: strong-password
        container_name: ccdb-db
        volumes:
          - ~/docker-volumes/ccdb/db:/var/lib/
    prometheus:
        image: prom/prometheus:v2.28.1
        container_name: ccdb-prometheus
        user: root
        volumes:
            - ./prometheus:/etc/prometheus
            - ~/docker-volumes/ccdb/prometheus:/prometheus
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana:8.0.6
        container_name: ccdb-grafana
        user: root
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/config.ini:/etc/grafana/config.ini
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ~/docker-volumes/ccdb/grafana:/var/lib/grafana
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - 3001:3000