version: '3.9'

services:
    rabbitmq:
        image: rabbitmq:3.12.0-management
        container_name: ccdb-rabbitmq
        hostname: 'dev-rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        restart: unless-stopped
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        env_file: ./env/.env.rabbitmq
        volumes:
            - '~/docker-volumes/ccdb/rabbitmq:/var/lib/rabbitmq'

    perf-test:
        image: pivotalrabbitmq/perf-test:latest
        container_name: ccdb-perf-test
        depends_on:
            rabbitmq:
                condition: service_healthy
        env_file: ./env/.env.perf-test
        entrypoint: sh -c "java -jar /perf_test/perf-test.jar --uri $$RABBITMQ_URI --queue-pattern 'perf-queue-%d' --queue-pattern-from 1 --queue-pattern-to 5 --producers 80 --consumers 5 -q 100"
