apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://ccdb-prometheus:9090
      basicAuth: false
      isDefault: true
      editable: true
