version: '3.9'

services:
    backend:
        build:
            context: ../../
            dockerfile: ./docker/config/backend/Dockerfile
            args:
                PORT: 8000
        image: ${BACKEND_IMAGE}
        container_name: ${BACKEND_CONTAINER_NAME}
        depends_on:
            timescale:
                condition: service_healthy
            redis:
                condition: service_healthy
        env_file: ./.env.backend
        entrypoint: 'tail -f /dev/null'

    timescale:
        image: timescale/timescaledb:2.11.1-pg15
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d ccdb_test -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_DB: ccdb_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        container_name: ccdb-timescale-test
        command: ['-c', 'max_connections=10000']
    
    redis:
        image: redis:7.2.3
        container_name: ccdb-redis
        command:
            - /bin/sh
            - -c
            - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: password
